name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install package
        run: |
          pip install .[test]
      - name: Format check with black
        run: |
          black --check .
      - name: Format check with flake8
        run: |
          ruff check .
      - name: Type check with mypy
        run: |
          mypy src/dlong
      - name: Test with pytest
        run: |
          pytest -vv --cov-report term-missing --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
